services:
  - type: web
    name: web-circuitochame
    runtime: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
